; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:nodemcu-32s]
; platform = espressif32
; board = nodemcu-32s
; framework = arduino
; monitor_speed = 115200
; lib_deps = chrissb/ADS1X15@^1.0.0

[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino

monitor_speed = 115200

; define default I2C pins for this board
build_flags =
  -D I2C_SDA=21
  -D I2C_SCL=22

; ADS1X15 library
lib_deps =
  adafruit/Adafruit ADS1X15 @ ^2.5.0
